export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_ERROR: "LOGIN_ERROR" = "LOGIN_ERROR";
export const LOGIN_REJECT: "LOGIN_REJECT" = "LOGIN_REJECT";

export const USERS_REQUEST: "USERS_REQUEST" = "USERS_REQUEST";
export const USERS_SUCCESS: "USERS_SUCCESS" = "USERS_SUCCESS";
export const USERS_ERROR: "USERS_ERROR" = "USERS_ERROR";

export const PREVIEW_USER: "PREVIEW_USER" = "PREVIEW_USER";
export const UPDATE_USER: "UPDATE_USER" = "UPDATE_USER";

export const SAVE_REQUEST: "SAVE_REQUEST" = "SAVE_REQUEST";
export const SAVE_SUCCESS: "SAVE_SUCCESS" = "SAVE_SUCCESS";
export const SAVE_ERROR: "SAVE_ERROR" = "SAVE_ERROR";